import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* <body className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)] dark"> */}
      <body className="m-auto max-w-[1280px] dark">
        <div className="grid grid-rows-[auto_1fr_auto] min-h-screen">
          <header className="">
            <h1 className="m-auto text-5xl md:text-7xl whitespace-nowrap mb-4 w-fit bg-clip-text text-transparent bg-gradient-to-tr from-teal-200 to-teal-700">
              The Chart.
            </h1>
            <p className="text-2xl">Showing you the best in music, books, and podcasts</p>
          </header>
          {children}
          <footer>
            <p>Top 20 Media Explorer - D Evans, 2025</p>
          </footer>
        </div>
      </body>
    </html>
  )
}
